# generated by Neptune Namespaces v3.x.x
# file: perfs/ArtAtomicBaseline/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Matrix: require './Matrix'
  Point:  require './Point' 