# generated by Neptune Namespaces v3.x.x
# file: perfs/ArtAtomicBaseline/namespace.coffee

module.exports = (require '../namespace').addNamespace('ArtAtomicBaseline', class ArtAtomicBaseline extends Neptune.PackageNamespace)
