# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Nano.Geometry/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  NanoMatrix: require './NanoMatrix'
  NanoPoint:  require './NanoPoint' 