# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Nano.Geometry/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Art.Nano.Geometry', class Geometry extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
