# generated by Neptune Namespaces v3.x.x
# file: perfs/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Perfs', class Perfs extends Neptune.PackageNamespace
  @version: require('../../package.json').version
require './Art.Nano.Geometry/namespace';
require './ArtAtomicBaseline/namespace';
require './JavaScriptBaseline/namespace'