# generated by Neptune Namespaces v3.x.x
# file: Art.Nano.Geometry/index.coffee

module.exports = require './namespace'
module.exports
.includeInNamespace require './Geometry'
.addModules
  NanoAtomicBase: require './NanoAtomicBase'
  NanoMatrix:     require './NanoMatrix'    
  NanoPoint:      require './NanoPoint'     
  NanoRectangle:  require './NanoRectangle' 
  StandardImport: require './StandardImport'