# generated by Neptune Namespaces v3.x.x
# file: Art.Nano.Geometry/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Art.Nano.Geometry', class Geometry extends Neptune.PackageNamespace
  @version: require('../../package.json').version
