# generated by Neptune Namespaces v3.x.x
# file: perfs/JavaScriptBaseline/namespace.coffee

module.exports = (require '../namespace').addNamespace('JavaScriptBaseline', class JavaScriptBaseline extends Neptune.PackageNamespace)
